jobs:
  build:
    environment:
      name: production-${{ matrix.cross.name }}
      url: https://github.com/Beuterei/hacs-package-manager/releases/download/${{ github.ref_name }}/hpm-${{ matrix.cross.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.20

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun build src/hpm.ts --compile --minify --target=${{ matrix.cross.target }}

      - env:
          GITHUB_TOKEN: ${{ secrets.CI }}
        name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          asset_content_type: application/octet-stream
          asset_name: hpm-${{ matrix.cross.name }}
          asset_path: hpm
          upload_url: ${{ github.event.release.upload_url }}
    strategy:
      matrix:
        cross:
          - name: linux-x64-baseline
            target: bun-linux-x64-baseline
          - name: linux-x64-modern
            target: bun-linux-x64-modern
          - name: linux-x64-musl-baseline
            target: bun-linux-x64-musl-baseline
          - name: linux-x64-musl-modern
            target: bun-linux-x64-musl-modern
          - name: macos-x64
            target: bun-darwin-x64-modern
          - name: macos-arm64
            target: bun-darwin-arm64-modern
          - name: windows-x64-baseline
            target: bun-windows-x64-baseline
          - name: windows-x64-modern
            target: bun-windows-x64-modern
          - name: arm
            target: bun-linux-arm64
          - name: arm-musl
            target: bun-linux-arm64-musl
name: "Publish a new version"

on:
  release:
    types:
      - created
