name: 'Publish a new version'

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, macos-14]
        os_short: [macos, linux, arm]
    environment:
      name: production-${{ matrix.os_short }}
      url: https://github.com/Beuterei/hacs-package-manager/releases/download/${{ github.ref_name }}/hpm-${{ matrix.os_short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.33

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun build src/hpm.ts --compile --minify

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CI }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: hpm
          asset_name: hpm-${{ matrix.os_short }}
          asset_content_type: application/octet-stream